### ISSUE TITLE
Add basic tests

### ISSUE THREAD

**Issue by limonte** [sweetalert2/vue-sweetalert2#5]
Basic tests proving that both `this.$swal` and `Vue.swal` are available should be easy to add.

https://vuejs.org/v2/guide/unit-testing.html

**Comment by avil13** [comment]
OK no problem

**Comment by avil13** [comment]
I wrote the tests that were needed. And added them to the repository.
https://github.com/sweetalert2/vue-sweetalert2

**Comment by limonte** [comment]
Perfect!
